# This file sets the basic flags for the LUAJIT compiler
if(WIN32)
    set(CMAKE_LUAJIT_COMPILE_OBJECT "\"${CMAKE_LUAJIT_COMPILER}\" -b \"<SOURCE>\" \"${CMAKE_BINARY_DIR}/<OBJECT>\"" CACHE STRING "CMAKE_LUAJIT_COMPILE_OBJECT" FORCE)
else()
    get_filename_component(LUAJIT_COMPILER_DIR ${CMAKE_LUAJIT_COMPILER} DIRECTORY)
    get_filename_component(LUAJIT_COMPILER_EXE ${CMAKE_LUAJIT_COMPILER} NAME)
    set(CMAKE_LUAJIT_COMPILE_OBJECT "cd \"${CMAKE_BINARY_DIR}\" && \"${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${LUAJIT_COMPILER_EXE}\" -b \"<SOURCE>\" \"${CMAKE_BINARY_DIR}/<OBJECT>\"" CACHE STRING "CMAKE_LUAJIT_COMPILE_OBJECT" FORCE)
endif()

set(CMAKE_LUAJIT_LINK_EXECUTABLE "${CMAKE_C_LINK_EXECUTABLE}" CACHE STRING "CMAKE_LUAJIT_LINK_EXECUTABLE" FORCE)
set(CMAKE_LUAJIT_CREATE_SHARED_LIBRARY "${CMAKE_C_CREATE_SHARED_LIBRARY}" CACHE STRING "CMAKE_LUAJIT_CREATE_SHARED_LIBRARY" FORCE)
set(CMAKE_LUAJIT_CREATE_SHARED_MODULE "${CMAKE_C_CREATE_SHARED_MODULE}" CACHE STRING "CMAKE_LUAJIT_CREATE_SHARED_MODULE" FORCE)

if(NOT DEFINED CMAKE_C_CREATE_STATIC_LIBRARY)
    set(CMAKE_LUAJIT_CREATE_STATIC_LIBRARY "${CMAKE_C_ARCHIVE_CREATE}" CACHE STRING "CMAKE_LUAJIT_CREATE_STATIC_LIBRARY" FORCE)
else()
    set(CMAKE_LUAJIT_CREATE_STATIC_LIBRARY "${CMAKE_C_CREATE_STATIC_LIBRARY}" CACHE STRING "CMAKE_LUAJIT_CREATE_STATIC_LIBRARY" FORCE)
endif()

# message(STATUS "Setting luajit linker:")
# message(STATUS "-- CMAKE_LUAJIT_LINK_EXECUTABLE: ${CMAKE_LUAJIT_LINK_EXECUTABLE}")
# message(STATUS "-- CMAKE_LUAJIT_CREATE_SHARED_LIBRARY: ${CMAKE_LUAJIT_CREATE_SHARED_LIBRARY}")
# message(STATUS "-- CMAKE_LUAJIT_CREATE_SHARED_MODULE: ${CMAKE_LUAJIT_CREATE_SHARED_MODULE}")
# message(STATUS "-- CMAKE_LUAJIT_CREATE_STATIC_LIBRARY: ${CMAKE_LUAJIT_CREATE_STATIC_LIBRARY}")

set(CMAKE_LUAJIT_INFORMATION_LOADED 1 CACHE STRING "CMAKE_LUAJIT_INFORMATION_LOADED" FORCE)